name: Linux

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: martypc
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Install dependencies
        run: >-
          sudo apt update && sudo apt install
          libasound2-dev
          libudev-dev

      - name: Cargo build
        run: cargo build -r --features ega

      - name: Copy files into install dir
        run: cp README.md target/release/martypc install

      - name: Rename install directory
        run: mv install martypc

      - name: Create artifact directory
        run: mkdir artifacts

      - name: Create artifact from install directory
        run: tar zcvf artifacts/martypc.tar.gz martypc

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: martypc-linux.tar.gz
          path: artifacts/martypc.tar.gz
